print("---Question 1---")
print("a.) i")
print("ALL Ug -> ALL KE")
input("")
print("a.)ii")
print("conservation of energy ->\n0+mg(L/2) = (1/2)m vP\nVp=sqrt(gL)")
input("")
print("a.)iii")
print("mg*h(release) = mg*hQ =>\nL/2=Lcos(theta_max) =>\ncos(theta_max)=1/2 =>\n Theta_max = 60")
input("")
print("b.)")
print("MOVE THE PEG UP. Since the lower string is HORIZONTAL at release, the sphere starts at the SAME HEIGHT AS THE PEG. ​​​​​​​​​​")
input("")
print("By CONSERVATION OF ENERGY, the sphere must rise to that SAME HEIGHT, where height is set by L·cos(θ_max). A HIGHER PEG means a HIGHER STARTING HEIGHT, requiring a LARGER θ_max on the right.​​​​​​")
input("")
print("----Question 2----")
print("a.)")
print("Fg point DOWN (SMALLER)\nFb point UP (BIGGER)")
input("")
print("b.)")
print("final:\nh(t)=(1/2)g[(4pip_wr^(2))/(3m)-1]t^(2)")
input("")
print("c.)")
print("Start at P0 and curve down")
input("")
print("d.)")
print("Sphere B has the SAME RADIUS as Sphere A, so it displaces the same volume of water and experiences the SAME BUOYANT FORCE. ")
input("")
print("However, Sphere B has DOUBLE the mass, so its gravitational force is doubled. This means the NET UPWARD FORCE on Sphere B is SMALLER than on Sphere A. ")
input("")
print("By Newtons Second Law, a = F_net/m, and since the net force DECREASED while the mass INCREASED, Sphere B ACCELERATION is smaller. ")
input("")
print("Both spheres travel the same distance from the bottom of the pool to the surface, and using h = 1/2at^2, a smaller acceleration requires a LONGER TIME to cover distance.")
input("")
print("Therefore, Sphere B takes longer than t₁ to reach the surface.​​​​​​​​​")
input("")
print("---Question 3---")
print("a.)")
print("Measure the applied torque T and the resulting angular acceleration a for several trials with different known torques, then plot T vs a — the slope of the best-fit line equals I.")
input("")
print("a.)ii")
print("I equals the slope of the best-fit line on a graph of T (y-axis) vs a (x-axis), since T = I a.")
input("")
print("Graphing")
print("X=W, Y=wi/wf: (0.13, 1.11) (0.31, 1.21) (0.44, 1.29) (0.59, 1.43) (0.76, 1.48)")
input("")
print("slope: (1.48 - 1.11)/(76-0.13) -> .37-.63 = .59\nR^(2)/I =>\n I=R^(2)/slope => .16/.59 =>\n.27  ")