print("---Question 1---")
print("a.) i")
print("ALL Ug -> ALL KE")
input("")
print("a.)ii")
print("conservation of energy ->\nMgL=1.2Mv^2 ->vp= sqrt(2gL)")
input("")
print("a.)iii")
print("Dstart=Lcos(theta)")
print("Dq=L-L/4 =3L/4")
print("Lcos(theta) = 3L/4")
print("cos(theta)=3/4")
print("theta=cos-1(.75) -> theta=41.4")
input("")
print("b.)")
print("MOVE THE PEG UP. Since the lower string is HORIZONTAL at release, the sphere starts at the SAME HEIGHT AS THE PEG. ​​​​​​​​​​")
input("")
print("By CONSERVATION OF ENERGY, the sphere must rise to that SAME HEIGHT, where height is set by L·cos(θ_max). A HIGHER PEG means a HIGHER STARTING HEIGHT, requiring a LARGER θ_max on the right.​​​​​​")
input("")
print("----Question 2----")
print("a.)")
print("Fg point DOWN (SMALLER)\nFb point UP (BIGGER)")
input("")
print("b.)")
print("F=ma")
print("F=Fb-Fg -> pwVg-mg")
print("V=3/4pir^2")
print("a=  (4pir^2 * pwg/3m) - g")
input("")
print("use: h(t)=1/2at^2")
print("final: h(t)=1/2 (4pir^2 pir^2 pwg/3mm)t^3")
input("")
print("c.)")
print("Start at P0 and curve down")
input("")
print("d.)")
print("Sphere B has the SAME RADIUS as Sphere A, so it displaces the same volume of water and experiences the SAME BUOYANT FORCE. ")
input("")
print("However, Sphere B has DOUBLE the mass, so its gravitational force is doubled. This means the NET UPWARD FORCE on Sphere B is SMALLER than on Sphere A. ")
input("")
print("By Newtons Second Law, a = F_net/m, and since the net force DECREASED while the mass INCREASED, Sphere B ACCELERATION is smaller. ")
input("")
print("Both spheres travel the same distance from the bottom of the pool to the surface, and using h = 1/2at^2, a smaller acceleration requires a LONGER TIME to cover distance.")
input("")
print("Therefore, Sphere B takes longer than t₁ to reach the surface.​​​​​​​​​")
input("")
print("---Question 3---")
print("a.)i")
print("torque, w, x")
input("")
print("a.)ii")
print("repeat expserement with different known t, ")
input("")
print("b.)i")
print("y-axis => torque")
print("x-axis => ras/s^2")
input("")
print("b.)ii")
print("slope = rotational inertia")
input("")
print("c.)i")
print("wi/wf = (MR^2/I0)+1\nrearrange =>\nwi/wf - 1 = (R^2/I0)M")
input("")
print("PLOTTING:\n (.13, .11), (.31, .21), (.44, .29), (.59, .43), (.76,.48)")