print("----FRQ SHM-----")
print("A")
print("Graph 1 shows KE of block while G2 shows the horazontal component\nKE is max at X=0 & min at X=pm D\nThe horazontal comp of Fnet is zero at x=0 and magnitude is max x=pmD")
input("")
print("B")
print("Graph 2 shows a restoreing force\nproportional to the displacement in the opposite direction")
input("")
print("C")
print("Period is incorrect\npropbelm states that P=2\nGraph p>2sec")
input("")
print("D")
print("track 2 P is longer, the blcok will have the same max speed over a longer distance")
input("")
print("E")
print("No, when d is the denom. as D up, Tdown.\nmeaning if the ramp gets longer: Pdown")
input("")
print("F")
print("The P of the sphere would be longer,KE is same but sphere KE->RKE")
input("")
print("Question2")
print("A")
print("t1=M0g(Lb/2)")
print("t2=(2.5M0)g(Lb/2)")
print("t=t1-t2")
print("Tnet=(3/4)M0gLb")
input("")
print("B")
print("Heavyer student -> 2.5M0 closer")
input("")
print("M0g(Lb/2)=(2.5M0)gr")
print("(Lb/2)=2.5r")
print("3Lb/10")
input("")
print("C")
print("Fs=M0g+2.5M0g")
print("Fd=(7/2)M0g")